[package]
name = "chromebook-keyd-config"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = "0.13.0"
libc = "0.2.149"
